{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a2b035b9",
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt \n",
    "import matplotlib.animation as animation\n",
    "import numpy as np\n",
    "from PIL import Image\n",
    "from matplotlib.patches import Circle"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "7a357fbb",
   "metadata": {},
   "outputs": [],
   "source": [
    "def cartesian(r, theta, phi):\n",
    "    \n",
    "    x = r*np.sin(theta)*np.cos(phi)\n",
    "    y = r*np.sin(theta)*np.sin(phi)\n",
    "    z = r*np.cos(theta)\n",
    "    \n",
    "    return x, y, z;\n",
    "\n",
    "def sphere(x, y, z):\n",
    "    \n",
    "    r = np.sqrt(x**2 + y**2 + z**2)\n",
    "    theta = np.arccos(z/r)\n",
    "    phi = np.arctan(x/y)\n",
    "    \n",
    "    return r, theta, phi;\n",
    "\n",
    "def radian(degree):\n",
    "    \n",
    "    return degree*2*np.pi/360.;"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "7bae7052",
   "metadata": {},
   "outputs": [],
   "source": [
    "def testgrid(theta_int, phi_int, r_source, Nx, Ny): # INPUT = intersection's coordinates OUTPUT = Color associated with the coordinates \n",
    "                                   # D'abord pour un point\n",
    "    \n",
    "    \n",
    "    RGB = np.zeros((Ny, Nx, 3))\n",
    "    \n",
    "    for i in range(0, Ny):\n",
    "        \n",
    "        for j in range(0, Nx):\n",
    "            \n",
    "            if 0 <= np.cos(phi_int[i][j]) < 1 and 0 <= np.sin(phi_int[i][j]) < 1 : # Green (Q1)\n",
    "                RGB[i][j] = (0, 256, 0) \n",
    "\n",
    "            if -1 <= np.cos(phi_int[i][j]) < 0 and 0 <= np.sin(phi_int[i][j]) < 1 :  # Red (Q1)\n",
    "                RGB[i][j] = (256, 0, 0) \n",
    "    \n",
    "            if -1 <= np.cos(phi_int[i][j]) < 0 and -1 <= np.sin(phi_int[i][j]) < 0 : # Yellow (Q3)\n",
    "                RGB[i][j] = (256, 256, 0) \n",
    "     \n",
    "            if 0 <= np.cos(phi_int[i][j]) < 1 and -1 <= np.sin(phi_int[i][j]) < 0 : #Blue (Q4)\n",
    "                RGB[i][j] = (0, 0, 256) \n",
    "            \n",
    "            x, y, z = cartesian(r_source, theta_int[i][j], phi_int[i][j])\n",
    "                \n",
    "            for k in range(0,9):\n",
    "                \n",
    "                y_lat = np.abs(r_source*np.sin(10*k*np.pi/180)) # 1 grille tous les 10 degrés\n",
    "                error_lat = r_source/100\n",
    "                \n",
    "                # LATITUDE\n",
    "                if  y_lat - error_lat < np.abs(y) < y_lat + error_lat :\n",
    "                     RGB[i][j] = (0, 0, 0)\n",
    "                    \n",
    "                # LONGITUDE \n",
    "            for k in range(0, 19):     \n",
    "                \n",
    "                alpha_long = 10*k*np.pi/180 # sin et pas cos car sin>0 de 0 à 180 et sin. < de 180 à 360\n",
    "                error_long = 2*np.pi/360 # Erreur de 1/2 radian\n",
    "                alpha = np.abs(np.arctan(x/z))\n",
    "                \n",
    "                if alpha_long - error_long < alpha < alpha_long + error_long:      \n",
    "                    RGB[i][j] = (0, 0, 0)   \n",
    "                                                                                                                          \n",
    "    \n",
    "    \n",
    "    return RGB;"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "33b7c7fb",
   "metadata": {},
   "outputs": [],
   "source": [
    "def geodesic(M, Rs, D, N, Nx, Ny, N_rot,xmax_screen, r_source, y_pix): # Compute the intersections between the geodesics and the SCREEN and \n",
    "                                                                           # and the OBJECT\n",
    "        \n",
    "\n",
    "    # INITIAL CONDITIONS   \n",
    "    \n",
    "   # N_rot = 12 # Maximal number of photon orbits before it leaves the black hole's surrounding.\n",
    "    dtheta = N_rot*2*np.pi/N \n",
    "    u = np.ones((Nx, N)) # Voir loop pour les CI (ATTENTION je mets 1 et pas 0 pour avoir de probleme si on divise par 0 )\n",
    "    u1 = np.zeros((Nx, N)) # derivative of u et Voir loop pour les CI\n",
    "    phi = np.ones((Nx, N)) \n",
    "    \n",
    "    # DEFINITIONS \n",
    "    \n",
    "    theta = np.zeros((Nx, N)) # the observer is located at x=0,y=0,z=D -> the first theta is 0\n",
    "    theta_int = np.ones(Nx)*Rs/2  # will contain the coordinates of the intersection with the OBJECT \n",
    "    phi_int = np.ones(Nx)*Rs/2 \n",
    "    phi = np.ones((Nx, N))    \n",
    "    \n",
    "    \n",
    "    # ALGORITHM\n",
    "    \n",
    "    for i in range(0, Nx): \n",
    "        \n",
    "        x_pix = -xmax_screen + 2*xmax_screen*i/(Nx-1) \n",
    "        di = np.sqrt(x_pix**2 + y_pix**2)\n",
    "        tan0 = di/D\n",
    "        \n",
    "        u[i][0] = 1/D\n",
    "        tampon = 0\n",
    "        u1[i][0] = 1/(D*tan0)\n",
    "  \n",
    "        if y_pix <= 0:\n",
    "           phi[i] = (-np.pi/2 + np.arcsin(x_pix/di))*phi[i]\n",
    "            \n",
    "        #elif y_pix == 0:\n",
    "             #phi[i] = 0*phi[i]   \n",
    "        \n",
    "        elif y_pix > 0:\n",
    "             phi[i] = (np.pi/2 - np.arcsin(x_pix/di))*phi[i]\n",
    "        \n",
    "        #print(\"pixel \", i) \n",
    "            \n",
    "        angle = 0\n",
    "        \n",
    "        for j in range(0, N-1): \n",
    "            \n",
    "            if 1/u[i][j] > Rs and tampon < 2: \n",
    "                 \n",
    "                # RUNGE-KUTTA 4 FOR u1 \n",
    "\n",
    "                f = (3/2)*Rs*u[i][j]**2 - u[i][j]\n",
    "                k1 = dtheta*f\n",
    "                f_k2 = (3/2)*Rs*(u[i][j] + k1/2)**2 - (u[i][j] + k1/2)\n",
    "                k2 = dtheta*f_k2\n",
    "                f_k3 = (3/2)*Rs*(u[i][j] + k2/2)**2 - (u[i][j] + k2/2)\n",
    "                k3 = dtheta*f_k3\n",
    "                f_k4 = (3/2)*Rs*(u[i][j] + k3)**2 - (u[i][j] + k3)\n",
    "                k4 = dtheta*f_k4\n",
    "                 \n",
    "                u1[i][j+1] = u1[i][j] + k1/6 + k2/3 + k3/3 + k4/6\n",
    "                \n",
    "                # RUNGE-KUTTA 4 FOR u\n",
    "                \n",
    "                f = u1[i][j]\n",
    "                k1 = dtheta*f\n",
    "                f_k2 = u1[i][j] + k1/2 \n",
    "                k2 = dtheta*f_k2\n",
    "                f_k3 = u1[i][j] + k2/2\n",
    "                k3 = dtheta*f_k3\n",
    "                f_k4 = u1[i][j] + k3\n",
    "                k4 = dtheta*f_k4\n",
    "            \n",
    "                u[i][j+1] = u[i][j] + k1/6 + k2/3 + k3/3 + k4/6\n",
    "                \n",
    "                # COMPUTE INTERSECTIONS VIA INTERPOLATION            \n",
    "                                                    \n",
    "                if 1/u[i][j] > r_source:  # Pas très précis mais bas les c\n",
    "                    tampon = 2 \n",
    "                    theta_int[i] = theta[i][j]\n",
    "                    phi_int[i] = phi[i][j]\n",
    "                    \n",
    "                \n",
    "                # CHANGE ANGLES AFTER HALF A REVOLUTION OF THE PHOTON\n",
    "                \n",
    "                if angle % 2 == 0:\n",
    "                    theta[i][j+1] = theta[i][j] + dtheta\n",
    "                \n",
    "                if angle % 2 != 0:\n",
    "                    theta[i][j+1] = theta[i][j] - dtheta  \n",
    "                \n",
    "                if theta[i][j+1] > np.pi: # Après un demi tour, il faut reinitialiser theta car 0 < theta < pi\n",
    "                    theta[i][j+1] = np.pi\n",
    "                    angle = angle + 1 \n",
    "                    phi[i] = phi[i] + np.pi \n",
    "                    \n",
    "                if theta[i][j+1] < 0.: # Après un demi tour, il faut reinitialiser theta car 0 < theta < pi\n",
    "                    theta[i][j+1] = 0.\n",
    "                    angle = angle + 1 \n",
    "                    phi[i] = phi[i] + np.pi     \n",
    "                \n",
    "                #if angle>2:\n",
    "                        #print('pixel', i)\n",
    "                        #print(angle)\n",
    "                           \n",
    "            \n",
    "            elif 1/u[i][j] <= Rs: # Si photon dans le trou noir, on arrete le calcul des geod.\n",
    "                u[i][j+1] = u[i][j] \n",
    "                u1[i][j+1] = u1[i][j]   \n",
    "                theta[i][j+1] = theta[i][j] \n",
    "             \n",
    "                 \n",
    "    return theta_int, phi_int; # return the coordinates of each intersection"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "5465481c",
   "metadata": {},
   "outputs": [],
   "source": [
    "def pixel(screen, RGB, Nx, Ny):\n",
    "    \n",
    "    image = np.zeros((Ny, Nx, 3))\n",
    "    print(image.shape)\n",
    "    \n",
    "    \n",
    "    for i in range(0, Ny): # i copies the index (0,1,2,3,...) and y copies \n",
    "        \n",
    "        for j in range(0, Nx): #screen[4] non? \n",
    "            \n",
    "            if theta_int[i][j] != Rs/2:\n",
    "                image[i][j] =  RGB[Ny-1 - i][j]  # Attention les images sont créés a-pd coin superieur gaiche (0,0) avec PILLOW\n",
    "                image[i][j] = image[i][j]/256\n",
    "                         \n",
    "      \n",
    "    plt.imsave('simulation.png', image)\n",
    "    \n",
    "    return print(\"The simulation is done!\");       "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "aa7b061b",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "600\n",
      "RANGEE ------------------ 0\n",
      "RANGEE ------------------ 1\n",
      "RANGEE ------------------ 2\n",
      "RANGEE ------------------ 3\n",
      "RANGEE ------------------ 4\n",
      "RANGEE ------------------ 5\n",
      "RANGEE ------------------ 6\n",
      "RANGEE ------------------ 7\n",
      "RANGEE ------------------ 8\n",
      "RANGEE ------------------ 9\n",
      "RANGEE ------------------ 10\n",
      "RANGEE ------------------ 11\n",
      "RANGEE ------------------ 12\n",
      "RANGEE ------------------ 13\n",
      "RANGEE ------------------ 14\n",
      "RANGEE ------------------ 15\n",
      "RANGEE ------------------ 16\n",
      "RANGEE ------------------ 17\n",
      "RANGEE ------------------ 18\n",
      "RANGEE ------------------ 19\n",
      "RANGEE ------------------ 20\n",
      "RANGEE ------------------ 21\n",
      "RANGEE ------------------ 22\n",
      "RANGEE ------------------ 23\n",
      "RANGEE ------------------ 24\n",
      "RANGEE ------------------ 25\n",
      "RANGEE ------------------ 26\n",
      "RANGEE ------------------ 27\n",
      "RANGEE ------------------ 28\n",
      "RANGEE ------------------ 29\n",
      "RANGEE ------------------ 30\n",
      "RANGEE ------------------ 31\n",
      "RANGEE ------------------ 32\n",
      "RANGEE ------------------ 33\n",
      "RANGEE ------------------ 34\n",
      "RANGEE ------------------ 35\n",
      "RANGEE ------------------ 36\n",
      "RANGEE ------------------ 37\n",
      "RANGEE ------------------ 38\n",
      "RANGEE ------------------ 39\n",
      "RANGEE ------------------ 40\n",
      "RANGEE ------------------ 41\n",
      "RANGEE ------------------ 42\n",
      "RANGEE ------------------ 43\n",
      "RANGEE ------------------ 44\n",
      "RANGEE ------------------ 45\n",
      "RANGEE ------------------ 46\n",
      "RANGEE ------------------ 47\n",
      "RANGEE ------------------ 48\n",
      "RANGEE ------------------ 49\n",
      "RANGEE ------------------ 50\n",
      "RANGEE ------------------ 51\n",
      "RANGEE ------------------ 52\n",
      "RANGEE ------------------ 53\n",
      "RANGEE ------------------ 54\n",
      "RANGEE ------------------ 55\n",
      "RANGEE ------------------ 56\n",
      "RANGEE ------------------ 57\n",
      "RANGEE ------------------ 58\n",
      "RANGEE ------------------ 59\n",
      "RANGEE ------------------ 60\n",
      "RANGEE ------------------ 61\n",
      "RANGEE ------------------ 62\n",
      "RANGEE ------------------ 63\n",
      "RANGEE ------------------ 64\n",
      "RANGEE ------------------ 65\n",
      "RANGEE ------------------ 66\n",
      "RANGEE ------------------ 67\n",
      "RANGEE ------------------ 68\n",
      "RANGEE ------------------ 69\n",
      "RANGEE ------------------ 70\n",
      "RANGEE ------------------ 71\n",
      "RANGEE ------------------ 72\n",
      "RANGEE ------------------ 73\n",
      "RANGEE ------------------ 74\n",
      "RANGEE ------------------ 75\n",
      "RANGEE ------------------ 76\n",
      "RANGEE ------------------ 77\n",
      "RANGEE ------------------ 78\n",
      "RANGEE ------------------ 79\n",
      "RANGEE ------------------ 80\n",
      "RANGEE ------------------ 81\n",
      "RANGEE ------------------ 82\n",
      "RANGEE ------------------ 83\n",
      "RANGEE ------------------ 84\n",
      "RANGEE ------------------ 85\n",
      "RANGEE ------------------ 86\n",
      "RANGEE ------------------ 87\n",
      "RANGEE ------------------ 88\n",
      "RANGEE ------------------ 89\n",
      "RANGEE ------------------ 90\n",
      "RANGEE ------------------ 91\n",
      "RANGEE ------------------ 92\n",
      "RANGEE ------------------ 93\n",
      "RANGEE ------------------ 94\n",
      "RANGEE ------------------ 95\n",
      "RANGEE ------------------ 96\n",
      "RANGEE ------------------ 97\n",
      "RANGEE ------------------ 98\n",
      "RANGEE ------------------ 99\n",
      "RANGEE ------------------ 100\n",
      "RANGEE ------------------ 101\n",
      "RANGEE ------------------ 102\n",
      "RANGEE ------------------ 103\n",
      "RANGEE ------------------ 104\n",
      "RANGEE ------------------ 105\n",
      "RANGEE ------------------ 106\n",
      "RANGEE ------------------ 107\n",
      "RANGEE ------------------ 108\n",
      "RANGEE ------------------ 109\n",
      "RANGEE ------------------ 110\n",
      "RANGEE ------------------ 111\n",
      "RANGEE ------------------ 112\n",
      "RANGEE ------------------ 113\n",
      "RANGEE ------------------ 114\n",
      "RANGEE ------------------ 115\n",
      "RANGEE ------------------ 116\n",
      "RANGEE ------------------ 117\n",
      "RANGEE ------------------ 118\n",
      "RANGEE ------------------ 119\n",
      "RANGEE ------------------ 120\n",
      "RANGEE ------------------ 121\n",
      "RANGEE ------------------ 122\n",
      "RANGEE ------------------ 123\n",
      "RANGEE ------------------ 124\n",
      "RANGEE ------------------ 125\n",
      "RANGEE ------------------ 126\n",
      "RANGEE ------------------ 127\n",
      "RANGEE ------------------ 128\n",
      "RANGEE ------------------ 129\n",
      "RANGEE ------------------ 130\n",
      "RANGEE ------------------ 131\n",
      "RANGEE ------------------ 132\n",
      "RANGEE ------------------ 133\n",
      "RANGEE ------------------ 134\n",
      "RANGEE ------------------ 135\n",
      "RANGEE ------------------ 136\n",
      "RANGEE ------------------ 137\n",
      "RANGEE ------------------ 138\n",
      "RANGEE ------------------ 139\n",
      "RANGEE ------------------ 140\n",
      "RANGEE ------------------ 141\n",
      "RANGEE ------------------ 142\n",
      "RANGEE ------------------ 143\n",
      "RANGEE ------------------ 144\n",
      "RANGEE ------------------ 145\n",
      "RANGEE ------------------ 146\n",
      "RANGEE ------------------ 147\n",
      "RANGEE ------------------ 148\n",
      "RANGEE ------------------ 149\n",
      "RANGEE ------------------ 150\n",
      "RANGEE ------------------ 151\n",
      "RANGEE ------------------ 152\n",
      "RANGEE ------------------ 153\n",
      "RANGEE ------------------ 154\n",
      "RANGEE ------------------ 155\n",
      "RANGEE ------------------ 156\n",
      "RANGEE ------------------ 157\n",
      "RANGEE ------------------ 158\n",
      "RANGEE ------------------ 159\n",
      "RANGEE ------------------ 160\n",
      "RANGEE ------------------ 161\n",
      "RANGEE ------------------ 162\n",
      "RANGEE ------------------ 163\n",
      "RANGEE ------------------ 164\n",
      "RANGEE ------------------ 165\n",
      "RANGEE ------------------ 166\n",
      "RANGEE ------------------ 167\n",
      "RANGEE ------------------ 168\n",
      "RANGEE ------------------ 169\n",
      "RANGEE ------------------ 170\n",
      "RANGEE ------------------ 171\n",
      "RANGEE ------------------ 172\n",
      "RANGEE ------------------ 173\n",
      "RANGEE ------------------ 174\n",
      "RANGEE ------------------ 175\n",
      "RANGEE ------------------ 176\n",
      "RANGEE ------------------ 177\n",
      "RANGEE ------------------ 178\n",
      "RANGEE ------------------ 179\n",
      "RANGEE ------------------ 180\n",
      "RANGEE ------------------ 181\n",
      "RANGEE ------------------ 182\n",
      "RANGEE ------------------ 183\n",
      "RANGEE ------------------ 184\n",
      "RANGEE ------------------ 185\n",
      "RANGEE ------------------ 186\n",
      "RANGEE ------------------ 187\n",
      "RANGEE ------------------ 188\n",
      "RANGEE ------------------ 189\n",
      "RANGEE ------------------ 190\n",
      "RANGEE ------------------ 191\n",
      "RANGEE ------------------ 192\n",
      "RANGEE ------------------ 193\n",
      "RANGEE ------------------ 194\n",
      "RANGEE ------------------ 195\n",
      "RANGEE ------------------ 196\n",
      "RANGEE ------------------ 197\n",
      "RANGEE ------------------ 198\n",
      "RANGEE ------------------ 199\n",
      "RANGEE ------------------ 200\n",
      "RANGEE ------------------ 201\n",
      "RANGEE ------------------ 202\n",
      "RANGEE ------------------ 203\n",
      "RANGEE ------------------ 204\n",
      "RANGEE ------------------ 205\n",
      "RANGEE ------------------ 206\n",
      "RANGEE ------------------ 207\n",
      "RANGEE ------------------ 208\n",
      "RANGEE ------------------ 209\n",
      "RANGEE ------------------ 210\n",
      "RANGEE ------------------ 211\n",
      "RANGEE ------------------ 212\n",
      "RANGEE ------------------ 213\n",
      "RANGEE ------------------ 214\n",
      "RANGEE ------------------ 215\n",
      "RANGEE ------------------ 216\n",
      "RANGEE ------------------ 217\n",
      "RANGEE ------------------ 218\n",
      "RANGEE ------------------ 219\n",
      "RANGEE ------------------ 220\n",
      "RANGEE ------------------ 221\n",
      "RANGEE ------------------ 222\n",
      "RANGEE ------------------ 223\n",
      "RANGEE ------------------ 224\n",
      "RANGEE ------------------ 225\n",
      "RANGEE ------------------ 226\n",
      "RANGEE ------------------ 227\n",
      "RANGEE ------------------ 228\n",
      "RANGEE ------------------ 229\n",
      "RANGEE ------------------ 230\n",
      "RANGEE ------------------ 231\n",
      "RANGEE ------------------ 232\n",
      "RANGEE ------------------ 233\n",
      "RANGEE ------------------ 234\n",
      "RANGEE ------------------ 235\n",
      "RANGEE ------------------ 236\n",
      "RANGEE ------------------ 237\n",
      "RANGEE ------------------ 238\n",
      "RANGEE ------------------ 239\n",
      "RANGEE ------------------ 240\n",
      "RANGEE ------------------ 241\n",
      "RANGEE ------------------ 242\n",
      "RANGEE ------------------ 243\n",
      "RANGEE ------------------ 244\n",
      "RANGEE ------------------ 245\n",
      "RANGEE ------------------ 246\n",
      "RANGEE ------------------ 247\n",
      "RANGEE ------------------ 248\n",
      "RANGEE ------------------ 249\n",
      "RANGEE ------------------ 250\n",
      "RANGEE ------------------ 251\n",
      "RANGEE ------------------ 252\n",
      "RANGEE ------------------ 253\n",
      "RANGEE ------------------ 254\n",
      "RANGEE ------------------ 255\n",
      "RANGEE ------------------ 256\n",
      "RANGEE ------------------ 257\n",
      "RANGEE ------------------ 258\n",
      "RANGEE ------------------ 259\n",
      "RANGEE ------------------ 260\n",
      "RANGEE ------------------ 261\n",
      "RANGEE ------------------ 262\n",
      "RANGEE ------------------ 263\n",
      "RANGEE ------------------ 264\n",
      "RANGEE ------------------ 265\n",
      "RANGEE ------------------ 266\n",
      "RANGEE ------------------ 267\n",
      "RANGEE ------------------ 268\n",
      "RANGEE ------------------ 269\n",
      "RANGEE ------------------ 270\n",
      "RANGEE ------------------ 271\n",
      "RANGEE ------------------ 272\n",
      "RANGEE ------------------ 273\n",
      "RANGEE ------------------ 274\n",
      "RANGEE ------------------ 275\n",
      "RANGEE ------------------ 276\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "RANGEE ------------------ 277\n",
      "RANGEE ------------------ 278\n",
      "RANGEE ------------------ 279\n",
      "RANGEE ------------------ 280\n",
      "RANGEE ------------------ 281\n",
      "RANGEE ------------------ 282\n",
      "RANGEE ------------------ 283\n",
      "RANGEE ------------------ 284\n",
      "RANGEE ------------------ 285\n",
      "RANGEE ------------------ 286\n",
      "RANGEE ------------------ 287\n",
      "RANGEE ------------------ 288\n",
      "RANGEE ------------------ 289\n",
      "RANGEE ------------------ 290\n",
      "RANGEE ------------------ 291\n",
      "RANGEE ------------------ 292\n",
      "RANGEE ------------------ 293\n",
      "RANGEE ------------------ 294\n",
      "RANGEE ------------------ 295\n",
      "RANGEE ------------------ 296\n",
      "RANGEE ------------------ 297\n",
      "RANGEE ------------------ 298\n",
      "RANGEE ------------------ 299\n",
      "RANGEE ------------------ 300\n",
      "RANGEE ------------------ 301\n",
      "RANGEE ------------------ 302\n",
      "RANGEE ------------------ 303\n",
      "RANGEE ------------------ 304\n",
      "RANGEE ------------------ 305\n",
      "RANGEE ------------------ 306\n",
      "RANGEE ------------------ 307\n",
      "RANGEE ------------------ 308\n",
      "RANGEE ------------------ 309\n",
      "RANGEE ------------------ 310\n",
      "RANGEE ------------------ 311\n",
      "RANGEE ------------------ 312\n",
      "RANGEE ------------------ 313\n",
      "RANGEE ------------------ 314\n",
      "RANGEE ------------------ 315\n",
      "RANGEE ------------------ 316\n",
      "RANGEE ------------------ 317\n",
      "RANGEE ------------------ 318\n",
      "RANGEE ------------------ 319\n",
      "RANGEE ------------------ 320\n",
      "RANGEE ------------------ 321\n",
      "RANGEE ------------------ 322\n",
      "RANGEE ------------------ 323\n",
      "RANGEE ------------------ 324\n",
      "RANGEE ------------------ 325\n",
      "RANGEE ------------------ 326\n",
      "RANGEE ------------------ 327\n",
      "RANGEE ------------------ 328\n",
      "RANGEE ------------------ 329\n",
      "RANGEE ------------------ 330\n",
      "RANGEE ------------------ 331\n",
      "RANGEE ------------------ 332\n",
      "RANGEE ------------------ 333\n",
      "RANGEE ------------------ 334\n",
      "RANGEE ------------------ 335\n",
      "RANGEE ------------------ 336\n",
      "RANGEE ------------------ 337\n",
      "RANGEE ------------------ 338\n",
      "RANGEE ------------------ 339\n",
      "RANGEE ------------------ 340\n",
      "RANGEE ------------------ 341\n",
      "RANGEE ------------------ 342\n",
      "RANGEE ------------------ 343\n",
      "RANGEE ------------------ 344\n",
      "RANGEE ------------------ 345\n",
      "RANGEE ------------------ 346\n",
      "RANGEE ------------------ 347\n",
      "RANGEE ------------------ 348\n",
      "RANGEE ------------------ 349\n",
      "RANGEE ------------------ 350\n",
      "RANGEE ------------------ 351\n",
      "RANGEE ------------------ 352\n",
      "RANGEE ------------------ 353\n",
      "RANGEE ------------------ 354\n",
      "RANGEE ------------------ 355\n",
      "RANGEE ------------------ 356\n",
      "RANGEE ------------------ 357\n",
      "RANGEE ------------------ 358\n",
      "RANGEE ------------------ 359\n",
      "RANGEE ------------------ 360\n",
      "RANGEE ------------------ 361\n",
      "RANGEE ------------------ 362\n",
      "RANGEE ------------------ 363\n",
      "RANGEE ------------------ 364\n",
      "RANGEE ------------------ 365\n",
      "RANGEE ------------------ 366\n",
      "RANGEE ------------------ 367\n",
      "RANGEE ------------------ 368\n",
      "RANGEE ------------------ 369\n",
      "RANGEE ------------------ 370\n",
      "RANGEE ------------------ 371\n",
      "RANGEE ------------------ 372\n",
      "RANGEE ------------------ 373\n",
      "RANGEE ------------------ 374\n",
      "RANGEE ------------------ 375\n",
      "RANGEE ------------------ 376\n",
      "RANGEE ------------------ 377\n",
      "RANGEE ------------------ 378\n",
      "RANGEE ------------------ 379\n",
      "RANGEE ------------------ 380\n",
      "RANGEE ------------------ 381\n",
      "RANGEE ------------------ 382\n",
      "RANGEE ------------------ 383\n",
      "RANGEE ------------------ 384\n",
      "RANGEE ------------------ 385\n",
      "RANGEE ------------------ 386\n",
      "RANGEE ------------------ 387\n",
      "RANGEE ------------------ 388\n",
      "RANGEE ------------------ 389\n",
      "RANGEE ------------------ 390\n",
      "RANGEE ------------------ 391\n",
      "RANGEE ------------------ 392\n",
      "RANGEE ------------------ 393\n",
      "RANGEE ------------------ 394\n",
      "RANGEE ------------------ 395\n",
      "RANGEE ------------------ 396\n",
      "RANGEE ------------------ 397\n",
      "RANGEE ------------------ 398\n",
      "RANGEE ------------------ 399\n",
      "RANGEE ------------------ 400\n",
      "RANGEE ------------------ 401\n",
      "RANGEE ------------------ 402\n",
      "RANGEE ------------------ 403\n",
      "RANGEE ------------------ 404\n",
      "RANGEE ------------------ 405\n",
      "RANGEE ------------------ 406\n",
      "RANGEE ------------------ 407\n",
      "RANGEE ------------------ 408\n",
      "RANGEE ------------------ 409\n",
      "RANGEE ------------------ 410\n",
      "RANGEE ------------------ 411\n",
      "RANGEE ------------------ 412\n",
      "RANGEE ------------------ 413\n",
      "RANGEE ------------------ 414\n",
      "RANGEE ------------------ 415\n",
      "RANGEE ------------------ 416\n",
      "RANGEE ------------------ 417\n",
      "RANGEE ------------------ 418\n",
      "RANGEE ------------------ 419\n",
      "RANGEE ------------------ 420\n",
      "RANGEE ------------------ 421\n",
      "RANGEE ------------------ 422\n",
      "RANGEE ------------------ 423\n",
      "RANGEE ------------------ 424\n",
      "RANGEE ------------------ 425\n",
      "RANGEE ------------------ 426\n",
      "RANGEE ------------------ 427\n",
      "RANGEE ------------------ 428\n",
      "RANGEE ------------------ 429\n",
      "RANGEE ------------------ 430\n",
      "RANGEE ------------------ 431\n",
      "RANGEE ------------------ 432\n",
      "RANGEE ------------------ 433\n",
      "RANGEE ------------------ 434\n",
      "RANGEE ------------------ 435\n",
      "RANGEE ------------------ 436\n",
      "RANGEE ------------------ 437\n",
      "RANGEE ------------------ 438\n",
      "RANGEE ------------------ 439\n",
      "RANGEE ------------------ 440\n",
      "RANGEE ------------------ 441\n",
      "RANGEE ------------------ 442\n",
      "RANGEE ------------------ 443\n",
      "RANGEE ------------------ 444\n",
      "RANGEE ------------------ 445\n",
      "RANGEE ------------------ 446\n",
      "RANGEE ------------------ 447\n",
      "RANGEE ------------------ 448\n",
      "RANGEE ------------------ 449\n",
      "RANGEE ------------------ 450\n",
      "RANGEE ------------------ 451\n",
      "RANGEE ------------------ 452\n",
      "RANGEE ------------------ 453\n",
      "RANGEE ------------------ 454\n",
      "RANGEE ------------------ 455\n",
      "RANGEE ------------------ 456\n",
      "RANGEE ------------------ 457\n",
      "RANGEE ------------------ 458\n",
      "RANGEE ------------------ 459\n",
      "RANGEE ------------------ 460\n",
      "RANGEE ------------------ 461\n",
      "RANGEE ------------------ 462\n",
      "RANGEE ------------------ 463\n",
      "RANGEE ------------------ 464\n",
      "RANGEE ------------------ 465\n",
      "RANGEE ------------------ 466\n",
      "RANGEE ------------------ 467\n",
      "RANGEE ------------------ 468\n",
      "RANGEE ------------------ 469\n",
      "RANGEE ------------------ 470\n",
      "RANGEE ------------------ 471\n",
      "RANGEE ------------------ 472\n",
      "RANGEE ------------------ 473\n",
      "RANGEE ------------------ 474\n",
      "RANGEE ------------------ 475\n",
      "RANGEE ------------------ 476\n",
      "RANGEE ------------------ 477\n",
      "RANGEE ------------------ 478\n",
      "RANGEE ------------------ 479\n",
      "RANGEE ------------------ 480\n",
      "RANGEE ------------------ 481\n",
      "RANGEE ------------------ 482\n",
      "RANGEE ------------------ 483\n",
      "RANGEE ------------------ 484\n",
      "RANGEE ------------------ 485\n",
      "RANGEE ------------------ 486\n",
      "RANGEE ------------------ 487\n",
      "RANGEE ------------------ 488\n",
      "RANGEE ------------------ 489\n",
      "RANGEE ------------------ 490\n",
      "RANGEE ------------------ 491\n",
      "RANGEE ------------------ 492\n",
      "RANGEE ------------------ 493\n",
      "RANGEE ------------------ 494\n",
      "RANGEE ------------------ 495\n",
      "RANGEE ------------------ 496\n",
      "RANGEE ------------------ 497\n",
      "RANGEE ------------------ 498\n",
      "RANGEE ------------------ 499\n",
      "RANGEE ------------------ 500\n",
      "RANGEE ------------------ 501\n",
      "RANGEE ------------------ 502\n",
      "RANGEE ------------------ 503\n",
      "RANGEE ------------------ 504\n",
      "RANGEE ------------------ 505\n",
      "RANGEE ------------------ 506\n",
      "RANGEE ------------------ 507\n",
      "RANGEE ------------------ 508\n",
      "RANGEE ------------------ 509\n",
      "RANGEE ------------------ 510\n",
      "RANGEE ------------------ 511\n",
      "RANGEE ------------------ 512\n",
      "RANGEE ------------------ 513\n",
      "RANGEE ------------------ 514\n",
      "RANGEE ------------------ 515\n",
      "RANGEE ------------------ 516\n",
      "RANGEE ------------------ 517\n",
      "RANGEE ------------------ 518\n",
      "RANGEE ------------------ 519\n",
      "RANGEE ------------------ 520\n",
      "RANGEE ------------------ 521\n",
      "RANGEE ------------------ 522\n",
      "RANGEE ------------------ 523\n",
      "RANGEE ------------------ 524\n",
      "RANGEE ------------------ 525\n",
      "RANGEE ------------------ 526\n",
      "RANGEE ------------------ 527\n",
      "RANGEE ------------------ 528\n",
      "RANGEE ------------------ 529\n",
      "RANGEE ------------------ 530\n",
      "RANGEE ------------------ 531\n",
      "RANGEE ------------------ 532\n",
      "RANGEE ------------------ 533\n",
      "RANGEE ------------------ 534\n",
      "RANGEE ------------------ 535\n",
      "RANGEE ------------------ 536\n",
      "RANGEE ------------------ 537\n",
      "RANGEE ------------------ 538\n",
      "RANGEE ------------------ 539\n",
      "RANGEE ------------------ 540\n",
      "RANGEE ------------------ 541\n",
      "RANGEE ------------------ 542\n",
      "RANGEE ------------------ 543\n",
      "RANGEE ------------------ 544\n",
      "RANGEE ------------------ 545\n",
      "RANGEE ------------------ 546\n",
      "RANGEE ------------------ 547\n",
      "RANGEE ------------------ 548\n",
      "RANGEE ------------------ 549\n",
      "RANGEE ------------------ 550\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "RANGEE ------------------ 551\n",
      "RANGEE ------------------ 552\n",
      "RANGEE ------------------ 553\n",
      "RANGEE ------------------ 554\n",
      "RANGEE ------------------ 555\n",
      "RANGEE ------------------ 556\n",
      "RANGEE ------------------ 557\n",
      "RANGEE ------------------ 558\n",
      "RANGEE ------------------ 559\n",
      "RANGEE ------------------ 560\n",
      "RANGEE ------------------ 561\n",
      "RANGEE ------------------ 562\n",
      "RANGEE ------------------ 563\n",
      "RANGEE ------------------ 564\n",
      "RANGEE ------------------ 565\n",
      "RANGEE ------------------ 566\n",
      "RANGEE ------------------ 567\n",
      "RANGEE ------------------ 568\n",
      "RANGEE ------------------ 569\n",
      "RANGEE ------------------ 570\n",
      "RANGEE ------------------ 571\n",
      "RANGEE ------------------ 572\n",
      "RANGEE ------------------ 573\n",
      "RANGEE ------------------ 574\n",
      "RANGEE ------------------ 575\n",
      "RANGEE ------------------ 576\n",
      "RANGEE ------------------ 577\n",
      "RANGEE ------------------ 578\n",
      "RANGEE ------------------ 579\n",
      "RANGEE ------------------ 580\n",
      "RANGEE ------------------ 581\n",
      "RANGEE ------------------ 582\n",
      "RANGEE ------------------ 583\n",
      "RANGEE ------------------ 584\n",
      "RANGEE ------------------ 585\n",
      "RANGEE ------------------ 586\n",
      "RANGEE ------------------ 587\n",
      "RANGEE ------------------ 588\n",
      "RANGEE ------------------ 589\n",
      "RANGEE ------------------ 590\n",
      "RANGEE ------------------ 591\n",
      "RANGEE ------------------ 592\n",
      "RANGEE ------------------ 593\n",
      "RANGEE ------------------ 594\n",
      "RANGEE ------------------ 595\n",
      "RANGEE ------------------ 596\n",
      "RANGEE ------------------ 597\n",
      "RANGEE ------------------ 598\n",
      "RANGEE ------------------ 599\n"
     ]
    }
   ],
   "source": [
    "# DONNEES DE LA SIMULATION\n",
    "\n",
    "M = 10**1 # Black hole mass\n",
    "Rs = 2*M # Schwarzschild radius \n",
    "N_rot = 10 # Number of steps\n",
    "N = 360*5\n",
    "r_source = Rs*10**2\n",
    "\n",
    "# CAMERA'S SETTINGS (FIXED, does not change if we approach the black hole)\n",
    "\n",
    "D = Rs*10 # Distance between the camera and the black hole \n",
    "hfov = (120/180)*np.pi # Horizontal FoV of the camera\n",
    "vfov = (120/180)*np.pi # Vertical FoV of the camera\n",
    "z_screen = 0. # Where the image is formed\n",
    "xmax_screen = np.tan(hfov/2)*D \n",
    "ymax_screen = np.tan(vfov/2)*D # OPTIONAL: Conserve the same aspect ratio of the background image\n",
    "ratio = xmax_screen/ymax_screen\n",
    "\n",
    "Nx = 600 # Number of x-pixel\n",
    "Ny = int(Nx/ratio)    # Conserve the same aspect ratio of the background image  NOMBRE PAIR DE PIXELS!!!\n",
    "print(Ny)\n",
    "\n",
    "screen = (-xmax_screen, ymax_screen, xmax_screen, -ymax_screen)\n",
    "\n",
    "theta_int = np.ones((Ny, Nx))\n",
    "phi_int = np.ones((Ny, Nx))\n",
    "\n",
    "for i in range(0, Ny):\n",
    "    y_pix =  -ymax_screen + 2*ymax_screen*i/(Ny-1)\n",
    "    print(\"RANGEE ------------------\", i)\n",
    "    theta_int[i], phi_int[i] = geodesic(M, Rs, D, N, Nx, Ny, N_rot, xmax_screen, r_source, y_pix)      "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "81e4f90c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(200, 200, 3)\n",
      "The simulation is done!\n"
     ]
    }
   ],
   "source": [
    "RGB = np.zeros((Ny, Nx, 3))\n",
    "\n",
    "RGB = testgrid(theta_int, phi_int, r_source, Nx, Ny)\n",
    "\n",
    "pixel(screen, RGB, Nx, Ny)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5e4cbac3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
